backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/assets/images" # Media files will be stored in the repo under static/images/uploads
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "staffProfiles"
    label: "profiles"
    folder: "src/staffProfiles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Image", name: "imageAlt", widget: "image"}
      - {label: "Name", name: "Name", widget: "string"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "faq"
    label: "faq"
    folder: "src/faq"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
